project:
  type: website
  output-dir: _site

website:
  site-url: "https://huzaifrahim.github.io"
  navbar:
    background: "#1a1c2c"
    container: true
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: videos.qmd
        text: Videos
      - href: education.qmd
        text: Education
      - href: experience.qmd
        text: Experience
      - href: about.qmd
        text: About

format:
  html:
    theme: minimal
    css:
      - styles.css?v=2
    toc: false
    mainfont: "Inter"
    resources:
      - googlefcbd9973d8740692.html
      - sitemap.xml
